// <auto-generated />
using System;
using DarkMyst.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DarkMyst.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_access_token");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.BattleChecksumMismatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("ClientChecksum")
                        .HasColumnType("text")
                        .HasColumnName("client_checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncounterId")
                        .HasColumnType("text")
                        .HasColumnName("encounter_id");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text")
                        .HasColumnName("request_json");

                    b.Property<string>("ServerChecksum")
                        .HasColumnType("text")
                        .HasColumnName("server_checksum");

                    b.HasKey("Id")
                        .HasName("pk_battle_checksum_mismatches");

                    b.ToTable("battle_checksum_mismatches", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.EvolveHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentVersion")
                        .HasColumnType("text")
                        .HasColumnName("content_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Focus")
                        .HasColumnType("text")
                        .HasColumnName("focus");

                    b.Property<string>("FodderInstanceIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("fodder_instance_ids_json");

                    b.Property<string>("FromCharacterId")
                        .HasColumnType("text")
                        .HasColumnName("from_character_id");

                    b.Property<int>("GainedBonusPerMille")
                        .HasColumnType("integer")
                        .HasColumnName("gained_bonus_per_mille");

                    b.Property<int>("GoldSpent")
                        .HasColumnType("integer")
                        .HasColumnName("gold_spent");

                    b.Property<string>("MaterialsSpentJson")
                        .HasColumnType("text")
                        .HasColumnName("materials_spent_json");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("ResultCharacterId")
                        .HasColumnType("text")
                        .HasColumnName("result_character_id");

                    b.Property<string>("ResultInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("result_instance_id");

                    b.Property<string>("SubjectInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("subject_instance_id");

                    b.Property<int>("TotalBonusPerMille")
                        .HasColumnType("integer")
                        .HasColumnName("total_bonus_per_mille");

                    b.HasKey("Id")
                        .HasName("pk_evolve_history");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_evolve_history_owner_id");

                    b.ToTable("evolve_history", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.ExpeditionRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContentVersion")
                        .HasColumnType("text")
                        .HasColumnName("content_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lifecycle");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("StageId")
                        .HasColumnType("text")
                        .HasColumnName("stage_id");

                    b.Property<string>("StateJson")
                        .HasColumnType("text")
                        .HasColumnName("state_json");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_expedition_runs");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_expedition_runs_owner_id");

                    b.ToTable("expedition_runs", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.IdempotencyRecordEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AccountId", "Endpoint", "Key")
                        .HasName("pk_idempotency_records");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.InventoryMaterialEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<string>("MaterialId")
                        .HasColumnType("text")
                        .HasColumnName("material_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.HasKey("AccountId", "MaterialId")
                        .HasName("pk_inventory_materials");

                    b.ToTable("inventory_materials", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.LedgerEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RefId")
                        .HasColumnType("text")
                        .HasColumnName("ref_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.LinkedIdentityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_linked_identities");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_linked_identities_account_id");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_linked_identities_provider_external_id");

                    b.ToTable("linked_identities", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.OwnedCharacterEntity", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("CharacterId")
                        .HasColumnType("text")
                        .HasColumnName("character_id");

                    b.Property<string>("ContentVersion")
                        .HasColumnType("text")
                        .HasColumnName("content_version");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("focus");

                    b.Property<int>("InheritedBonusPerMille")
                        .HasColumnType("integer")
                        .HasColumnName("inherited_bonus_per_mille");

                    b.Property<bool>("IsInUse")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_use");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("ObtainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("obtained_at");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.HasKey("InstanceId")
                        .HasName("pk_owned_characters");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_owned_characters_owner_id");

                    b.ToTable("owned_characters", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.PendingLinkEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExistingAccountId")
                        .HasColumnType("text")
                        .HasColumnName("existing_account_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("GuestAccountId")
                        .HasColumnType("text")
                        .HasColumnName("guest_account_id");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_pending_links");

                    b.ToTable("pending_links", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.SavedTeamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LeaderSlot")
                        .HasColumnType("integer")
                        .HasColumnName("leader_slot");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_saved_teams");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_saved_teams_owner_id");

                    b.ToTable("saved_teams", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.SavedTeamMemberEntity", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.HasKey("TeamId", "Slot")
                        .HasName("pk_saved_team_members");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_saved_team_members_instance_id");

                    b.ToTable("saved_team_members", (string)null);
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.InventoryMaterialEntity", b =>
                {
                    b.HasOne("DarkMyst.Api.Data.Entities.AccountEntity", null)
                        .WithMany("Materials")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_materials_accounts_account_id");
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.LinkedIdentityEntity", b =>
                {
                    b.HasOne("DarkMyst.Api.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_linked_identities_accounts_account_id");
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.OwnedCharacterEntity", b =>
                {
                    b.HasOne("DarkMyst.Api.Data.Entities.AccountEntity", null)
                        .WithMany("Characters")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_owned_characters_accounts_owner_id");
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.SavedTeamMemberEntity", b =>
                {
                    b.HasOne("DarkMyst.Api.Data.Entities.SavedTeamEntity", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_team_members_saved_teams_team_id");
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DarkMyst.Api.Data.Entities.SavedTeamEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
